name: tsenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - statsmodels
  - numpy
  - pandas
  - scikit-learn
  - pip
  - pip:
      - lxml==5.1.0
      - pandas-datareader==0.10.0
      - pmdarima==2.0.4
